### ISSUE TITLE
Traceback  error

### ISSUE THREAD

**Issue by Tobe2d** [ntdviet/comfyui-ext#3]
I am getting this error 

```
Traceback (most recent call last):
  File "D:\Ai__Project\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Ai__Project\\ComfyUI\\custom_nodes\\comfyui-ext\\__init__.py'

Cannot import D:\Ai__Project\ComfyUI\custom_nodes\comfyui-ext module for custom nodes: [Errno 2] No such file or directory: 'D:\\Ai__Project\\ComfyUI\\custom_nodes\\comfyui-ext\\__init__.py'
```

Could you point to me how to fix?

**Comment by ArtHommage** [comment]
Create "__init__.py" in the root of the node directory, and put this code in it:

```
from .custom_nodes.gcLatentTunnel.gcLatentTunnel import gcLatentTunnel, NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

__all__ = ['gcLatentTunnel', 'NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
```

I do find it odd this is missing also.
